<?php

/**
 * @file
 * Contains drupal_assignment.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function drupal_assignment_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.drupal_assignment':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Site location block for Drupal Assignment') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function drupal_assignment_theme() {
  return [
    'site_location_block' => [
      'variables' => [
        'city' => NULL,
        'country' => NULL,
        'current_time' => NULL,
      ],
    ],
  ];
}
